### ISSUE TITLE
Feature Request: more options please

### ISSUE THREAD

**Issue by virgilwashere** [dvershinin/lastversion#1]
# Feature Request

Can you add some more options?

- [Feature Request](#feature-request)
  * [potential usage output](#potential-usage-output)
  * [command line options](#command-line-options)
    + [verbose](#verbose)
    + [query this repo](#query-this-repo)
    + [internal version](#internal-version)
    + [pre-releases](#pre-releases)
    + [download urls](#download-urls)
      - [zipball vs tarball](#zipball-vs-tarball)
    + [--api](#--api)

## potential usage output

```console
usage: lastversion [-hvV] [--pre] [--api|--nosniff] [--novalidate] [--assets] REPO

Get latest release from GitHub.

positional arguments:
  REPO             	GitHub repository in format owner/name

optional arguments:
# -h, --help    	show this help message and exit
  -V, --version 	show version and exit
  -v, --verbose		Show URIs being tested	

  --pre		   		Include pre-releases in potential versions
  --assets			Show download URL of assets for last version
  --nosniff, --api	use api.github.com
# --novalidate

  --self        	show the latest version of 'lastversion'
```

### verbose

Show the URIs being tested, especially in the `for release in r.find_all` loop.

Also useful info if `--pre` happens.

### query this repo

Currently:

```console
$ lastversion dvershinin/lastversion
0.0.5

$ lastversion --nosniff dvershinin/lastversion
0.0.8

$ hub api /repos/dvershinin/lastversion/releases/latest \
  | jq -r '.tag_name, .html_url, .tarball_url'
0.0.8
https://github.com/dvershinin/lastversion/releases/tag/0.0.8
https://api.github.com/repos/dvershinin/lastversion/tarball/0.0.8
```

New:

```console
$ lastversion --self
0.0.8
```

### internal version

Add an internal version number

```console
$ lastversion --version
lastversion 0.0.8 (c) 2019 ...
```

Verbose mode shows binary version and repo?

```console
$ lastversion --verbose --version
lastversion 0.0.8 (c) 2019 ...
github release: 0.0.9
```

### pre-releases

I ended up here today, via one of the `curl | jq` gists because I was looking for a way to find pre-releases.  In this case:

```console
$ lastversion mautic/mautic
2.15.1
```

But I'm looking for a direct download link for `2.15.2-beta`... which I worked out during this post.

```console
$ tag=$( hub api /repos/mautic/mautic/tags | jq -r '.[0].name')
$ echo $tag
2.15.2-beta
$ hub api /repos/mautic/mautic/releases/tags/${tag} | jq -r '.tag_name, .assets[].browser_download_url'
2.15.2-beta
https://github.com/mautic/mautic/releases/download/2.15.2-beta/2.15.2-beta-update.zip
https://github.com/mautic/mautic/releases/download/2.15.2-beta/2.15.2-beta.zip
```

```console
$ lastversion --pre mautic/mautic
2.15.2-beta
```

### download urls

Show download URL of assets for last version found.  
Be that: `.assets[].browser_download_url` for correctly formatted Releases, or 
`.tarball_url`/`.zipball_url` when you have to use  '/releases/:tag`

#### zipball vs tarball

platform check, win32 = zipball ?

### --api

Because I don't under `--nosniff` at all :grin:

----

Thanks in advance.

Virgil

**Comment by dvershinin** [comment]
Good suggestions. I will implement them (some with lower priority though, because at least for me the main target is getting the last stable version and only that).

The default behavior is to just fetch HTML of releases page and parse that. Only if nothing is found there, the API call is attempted. The `--nosniff` option will directly use only in the GitHub API being used (no parsing), so it's more like a showcase how default GitHub API isn't working as expected.

**Comment by dvershinin** [comment]
@virgilwashere you might just do this with the new version:

    wget $(lastversion --pre --assets mautic/mautic)

Then it downloads both :)

    file *.zip
    2.15.2-beta-update.zip: Zip archive data, at least v2.0 to extract
    2.15.2-beta.zip:        Zip archive data, at least v2.0 to extract

I see it somewhat useful now, for repos which for instance having md5 checksums in separate files.

**Comment by virgilwashere** [comment]
Thank you!

In combination with these shell functions, `lastversion` will simplify updating prerequisites for deployments!!

```bash
version_lte() { printf '%s\n%s' "${1}" "${2}" | $( command -v sort) -C -V; }
version_lt() { ! version_lte "${2}" "${1}"; }
```

Virgil

**Comment by virgilwashere** [comment]
`--self` would still be nice to have.

```console
--self        	show the latest version of 'lastversion'
```

Or maybe `--verbose --version` actually checks github releases for `dvershinin/lastversion` ???

Thanks for `0.1.0` release!

**Comment by dvershinin** [comment]
@virgilwashere I didn't (at least yet) add the `--self` because it makes parsing options code complex (for me : ) . 

I'm using similar bash function in my scripts:

```
function version_gt() {
  test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
}
```

It occurred to me now that it might be useful to integrate version comparison into `lastversion` itself. As in maybe like this:

```bash
CURRENTLY_BUILT_VER=1.2.3 # stored somewhere, e.g. spec file in my case
LASTVER=$(lastversion repo/owner --newer-than $CURRENTLY_BUILT_VER)
if [ $? -eq 0 ]; then
  # LASTVER is newer, update and trigger build
  ....
```
With exit status `1` for version lookup failure and `2` for comparison failure if required to distinguish them.

**Comment by dvershinin** [comment]
Got the `self` working as special value of repository argument, so it's not flag, e.g.

    lastversion self

Another addition is being able to lookup by a single word (search API does not allow for good caching at all, so careful with rate limits), but it's quite fun seeing this work:

    lastversion linux # > 5.2
    lastversion linux --pre # > 5.3rc2
    lastversion ngx_pagespeed # > 1.13.35.2 works even though argument does not match repo name, which is incubator-pagespeed-ngx

Or this, to check if you use latest Linux kernel:

```
NEWER_KERNEL=$(lastversion linux -gt $(uname -r | cut -d '-' -f 1))
if [ $? -eq 0 ]; then
  echo "I better update my kernel now, because ${KERNEL} is there"
else 
  echo "My kernel is latest and greatest."
fi
```
