### ISSUE TITLE
verify flag for sessions

### ISSUE THREAD

**Issue by eFAILution** [dvershinin/lastversion#105]
requests etc. often include options for ssl_verify and the such for those instances when the host server doesn't support.  Would be convenient if your sessions adopted the same functionality.  For this gitlab session it would be `return self.get(url, verify=False)`

https://github.com/dvershinin/lastversion/blob/c7b2d0547ff6a2a913872d8dc97fb25ff19ee73e/lastversion/GitLabRepoSession.py#L38

**Comment by dvershinin** [comment]
I'm not sure what you mean there. Do you just want to disable TLS verification for all GitLab requests? Doesn't seem like a good thing to do.

**Comment by eFAILution** [comment]
> I'm not sure what you mean there. Do you just want to disable TLS verification for all GitLab requests? Doesn't seem like a good thing to do.

Not disable by default, but give the option to. Not everyone has TLS set up on their private Gitlab instances. It’s why requests has an argument for verify.

**Comment by dvershinin** [comment]
Wouldn't it be a better option to import the root CA which issued the self signed TLS certificate, on your system?
