### ISSUE TITLE
Bump up the cachecontrol pacakge 

### ISSUE THREAD

**Issue by kaleocheng** [dvershinin/lastversion#106]
Hi, I was trying to package this  tool into [nixpkgs](https://github.com/NixOS/nixpkgs)  but I found it using a fixed cachecontrol package. 

https://github.com/dvershinin/lastversion/blob/master/setup.py#L25
```
    # latest 0.12.12 uses filelock instead of lockfile,
    # we have to update our packaging before switching to it
    'cachecontrol==0.12.6',
```

any chance to upgrade it to the  latest version?

**Comment by dvershinin** [comment]
Released a new version with `'cachecontrol<=0.12.11'`. Hope this helps.
