### ISSUE TITLE
The AppImage is downloaded, but os.chmod fails

### ISSUE THREAD

**Issue by consumptionof** [dvershinin/lastversion#107]
I'm using Fedora 38, with lastversion 3.0.1 installed per the instructions for RPM-based distributions. I run `lastversion install OneDriveGUI` and get this result:
```
Downloaded OneDriveGUI-1.0.3-x86_64.AppImage: : 65872.0KB [00:01, 40607.61KB/s]                               
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 33, in <module>
    sys.exit(load_entry_point('lastversion==3.0.1', 'console_scripts', 'lastversion')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lastversion/lastversion.py", line 597, in main
    return install_app_image(app_images[0], install_name=args.repo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lastversion/lastversion.py", line 385, in install_app_image
    os.chmod(app_file_name, 0o755)  # skipcq: BAN-B103
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/john/Applications/OneDriveGUI'
```
When I look in my Applications directory, OneDriveGUI-1.0.3-x86_64.AppImage is there. Is it supposed to rename the downloaded file to "OneDriveGUI"?

**Comment by dvershinin** [comment]
@consumptionof please check lastversion v3.2.1 with the fix for it.

**Comment by consumptionof** [comment]
Now it says `ERROR: No assets found to install` when I try `lastversion install OneDriveGUI` with lastversion 3.3.0. Was it alright before?

**Comment by dvershinin** [comment]
@consumptionof There was a regression apparently, added it to tests. Please try with lastversion 3.3.1

**Comment by consumptionof** [comment]
@dvershinin It looks like it's working now, thanks!
