### ISSUE TITLE
Does not differntiate between tags and releases on github repos

### ISSUE THREAD

**Issue by ithinkido** [dvershinin/lastversion#108]
In some rare cases, the tag version is not the same as the release version , and when pointing  lastversion to the relese page , it still seems to be pulling the tag version and asset info. 

eg , this [page](https://github.com/evil-mad/axidraw/releases)  

when running 
```lastversion --assets  https://github.com/evil-mad/axidraw/releases```
It does not return the assets from the relse page, but rather the assests from the [tags page ](https://github.com/evil-mad/axidraw/tags)
My goal is to run 
```lastversion --assets --filter lin-x86 unzip https://github.com/evil-mad/axidraw/releases -o ad```

**Comment by dvershinin** [comment]
I think what you're looking for is `--having-asset` switch: `lastversion --having-asset --assets --filter lin-x86 unzip https://github.com/evil-mad/axidraw/releases -o ad`

**Comment by ithinkido** [comment]
That is exactly what I needed. ! Thank you very much for the work you have done on the fantastic tool.
