### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by onedr0p** [dvershinin/lastversion#11]
Would be neat to add Gitlab support as well!

**Comment by dvershinin** [comment]
@onedr0p is there any reference Gitlab repo of interest?

**Comment by onedr0p** [comment]
What do you mean? Any gitlab repo would suffice.

**Comment by onedr0p** [comment]
Here's one I maintain

https://gitlab.com/onedr0p/sonarr-episode-prune/-/tags

**Comment by dvershinin** [comment]
lastversion https://gitlab.com/onedr0p/sonarr-episode-prune/

should work in the latest release :1st_place_medal:
