### ISSUE TITLE
[GitLab] Last version and tag missmatch

### ISSUE THREAD

**Issue by kovmir** [dvershinin/lastversion#134]
**Project with incorrect version**

https://gitlab.com/librewolf-community/browser/appimage

**To Reproduce**

I am not using tokens.

```
$ URL='https://gitlab.com/librewolf-community/browser/appimage'
$ lastversion $URL
120.0.1
$ lastversion --format tag $URL
v120.0-1
```

**Expected behavior**

`lastversion --format tag $URL` should have given out `v120.0.1-1`.

**Comment by dvershinin** [comment]
Added fix in lastversion 3.4.5
