### ISSUE TITLE
Some projects return incorrect versions when using gt param

### ISSUE THREAD

**Issue by Sithranduil** [dvershinin/lastversion#144]
**Project with incorrect version**

https://github.com/NockyCZ/CS2-Deathmatch/
https://github.com/Pisex/cs2-bans

**To Reproduce**

lastversion https://github.com/Pisex/cs2-bans -gt 2.5.2 ; echo $?
lastversion https://github.com/NockyCZ/CS2-Deathmatch -gt 1.0.2 ; echo $?

**Expected behavior**

The first command should return the 2.5.3 with the -gt params and with the exit code 0
The second command should return the 1.0.3 with the -gt params and with the exit code 0

**Program output**

```
lastversion https://github.com/Pisex/cs2-bans -gt 2.5.2 ; echo $?
2.5.2
2
```

```
lastversion https://github.com/NockyCZ/CS2-Deathmatch -gt 1.0.2 ; echo $?
2
0
```

**Comment by dvershinin** [comment]
Fixed in lastversion v3.5.0
