### ISSUE TITLE
Pre-release version being picked up as regular release

### ISSUE THREAD

**Issue by Sodki** [dvershinin/lastversion#147]
**Project with incorrect version**

https://pypi.org/project/pulumi-aws/

**To Reproduce**

```
lastversion pulumi-aws
```

**Expected behavior**

```
6.19.0
```

**Program output**

```
6.20.0
```

The pre-release version is being picked up as a release version.

![image](https://github.com/dvershinin/lastversion/assets/4172609/6665436f-ee6f-461b-a7c7-737b7c143f9a)

**Comment by vaz-ar** [comment]
I think that I may have the same issue with https://github.com/jesseduffield/lazygit/releases , where the last release is currently `v0.40.2`, but there is a [pre-0.41](https://github.com/jesseduffield/lazygit/releases/tag/pre-0.41) tag:

~~~bash
❯ lastversion --version
lastversion 3.5.0, up to date
❯ lastversion lazygit
0.41
~~~

**Comment by dvershinin** [comment]
@vaz-ar fixed in v3.5.1

**Comment by devzwf** [comment]
well do not seems to be fixed :

```
$ lastversion --version
lastversion 3.5.1, up to date
$ lastversion  https://github.com/tailscale/tailscale
1.61.0
$ lastversion --formal  https://github.com/tailscale/tailscale
1.60.1
$

**Comment by dvershinin** [comment]
@devzwf Please check with lastversion 3.5.2

**Comment by devzwf** [comment]
seems fixed 
``` #$  lastversion --version
lastversion 3.5.2, up to date
$ lastversion  https://github.com/tailscale/tailscale
1.62.0
$ lastversion  --formal https://github.com/tailscale/tailscale
1.62.0
$
```

**Comment by dvershinin** [comment]
@Sodki  are you still able to reproduce your issue with latest lastversion release?

**Comment by Sodki** [comment]
All seems to be good, thank you.
