### ISSUE TITLE
Release Candidate Pre Release not Shown

### ISSUE THREAD

**Issue by nobicycle** [dvershinin/lastversion#148]
**Project with incorrect version**
Joomla

Please put a web link to a project location that you're checking with `lastversion` here.
https://github.com/joomla/joomla-cms/releases

**To Reproduce**
lastversion --pre --assets  https://github.com/joomla/joomla-cms/releases

What command have you run, e.g. `lastversion <project location> --verbose`

**Expected behavior**

To show the Release_Candidate prre release

![2024-02-19 20 35 34 github com 39711405b77a](https://github.com/dvershinin/lastversion/assets/1372447/e055f616-fd52-4f30-bc0e-858df3ca7174)

What output you expect to receive, e.g. correct version in your opinion.

**Program output**
 ```
lastversion --pre --assets  https://github.com/joomla/joomla-cms/releases
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Full_Package.tar.gz
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Full_Package.tar.zst
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Full_Package.zip
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Update_Package.tar.gz
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Update_Package.tar.zst
https://github.com/joomla/joomla-cms/releases/download/5.1.0-alpha3/Joomla_5.1.0-alpha3-Alpha-Update_Package.zip


```
What output does `lastversion` give when being run?

**Current scope and support**

Thank you for submitting this issue/request! 🌟

Currently, my focus is on maintaining and enhancing features critical to GitHub releases. 
Fetching a release version from other sources is not a priority at the moment, neither supplementary feature like
zipball/tarball download, etc.

If your particular issue/feature/enhancement falls outside those priorities, and you believe this feature is important and would like to see it developed sooner, there are a few ways to help:

- **Contribute:** We welcome pull requests!
- **Donate:** If you're not able to contribute code but still want to support the addition of this feature, consider making a donation. Donations help prioritize and fund development efforts on features outside my current scope. [Donate here](https://github.com/sponsors/dvershinin).

Your support is greatly appreciated, and any contribution, be it code or donation, helps make `lastversion` better for everyone. 🚀

**Comment by dvershinin** [comment]
There's an alpha release https://github.com/joomla/joomla-cms/releases/tag/5.1.0-alpha3 so technically the output from `lastversion` is correct. The `--pre` switch is to return whatever latest pre-release/not-stable version there is. 5.1.0-alpha3 is a newer version than 5.0.3 rc, despite being tagged earlier. 

You can exclude non-desired stability or whitelist desired one. Will achieve same effect now:

```
lastversion --pre --assets https://github.com/joomla/joomla-cms/releases --exclude alpha
lastversion --pre --assets https://github.com/joomla/joomla-cms/releases --only rc
```

**Comment by nobicycle** [comment]
thanks
