### ISSUE TITLE
lastversion 3.5.0 requires cachecontrol<=0.12.11 but you have cachecontrol 0.14.0 which is incompatible, breaks lastversion when upgrading pip packages.

### ISSUE THREAD

**Issue by nizmogtr** [dvershinin/lastversion#149]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lastversion 3.5.0 requires cachecontrol<=0.12.11, but you have cachecontrol 0.14.0 which is incompatible.

**Comment by dvershinin** [comment]
`lastversion` indeed required cachecontrol<=0.12.11. Please install it from packages or in a virtualenv (e.g. via [`pip-safe`](https://github.com/dvershinin/pip-safe))
