### ISSUE TITLE
Problem fetching pulumi assets

### ISSUE THREAD

**Issue by xmstspider** [dvershinin/lastversion#150]
Hi,

thank you for an amazing tool!

I've got issue fetching assets from one GitHub project...

**Project with incorrect version**

[Pulumi](https://github.com/pulumi/pulumi/)

Tested and not working: `v3.108.0`, `v3.107.0`, `v3.106.0`, `v3.105.0`

**To Reproduce**

lastversion --filter . --assets https://github.com/pulumi/pulumi/ --download
lastversion --filter . --assets https://github.com/pulumi/pulumi/ --download --only 3.107.0

etc.

Source code download with `lastversion --filter . --assets https://github.com/pulumi/pulumi/ --download --source -su` works though.

**Expected behavior**

Fetch all 22 assets (source files omitted)

**Program output**

```
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 33, in <module>
    sys.exit(load_entry_point('lastversion==3.5.0', 'console_scripts', 'lastversion')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lastversion/lastversion.py", line 889, in main
    download_file(url, download_name)
  File "/usr/lib/python3.12/site-packages/lastversion/utils.py", line 286, in download_file
    response.raise_for_status()
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://codeload.github.com/pulumi/pulumi/tar.gz/pkg/v3.108.0/pulumi-pkg/v3.108.0
```

**Current scope and support**

Thank you for submitting this issue/request! 🌟

Currently, my focus is on maintaining and enhancing features critical to GitHub releases. 
Fetching a release version from other sources is not a priority at the moment, neither supplementary feature like
zipball/tarball download, etc.

If your particular issue/feature/enhancement falls outside those priorities, and you believe this feature is important and would like to see it developed sooner, there are a few ways to help:

- **Contribute:** We welcome pull requests!
- **Donate:** If you're not able to contribute code but still want to support the addition of this feature, consider making a donation. Donations help prioritize and fund development efforts on features outside my current scope. [Donate here](https://github.com/sponsors/dvershinin).

Your support is greatly appreciated, and any contribution, be it code or donation, helps make `lastversion` better for everyone. 🚀

**Comment by dvershinin** [comment]
@xmstspider fixed in v3.5.1
