### ISSUE TITLE
Zero padding is not done with CalVer

### ISSUE THREAD

**Issue by TheBlusky** [dvershinin/lastversion#159]
**Project with incorrect version**

https://github.com/pi-hole/docker-pi-hole

**To Reproduce**

lastversion pi-hole/docker-pi-hole

**Expected behavior**

2024.06.0

**Program output**

2024.6.0

**Comment by dvershinin** [comment]
If you need the original zero padding, use `lastversion https://github.com/pi-hole/docker-pi-hole --format tag` 
Lastversion will always strip leading zeros from the version components.

**Comment by TheBlusky** [comment]
Oh, I tried to look for this kind of option.

Thanks for pointing it out !
