### ISSUE TITLE
[Feature Request] --download should work with --filter and --assets

### ISSUE THREAD

**Issue by munkee** [dvershinin/lastversion#16]
`$ lastversion --assets --filter amd64.deb cli/cli `gives me the url of the file I want, but adding --download doesn't work.  I know that the README suggests wget `$(lastversion --assets --filter amd64.deb cli/cli)` but it would be nice to handle it without resorting to subshells or xargs.

**Comment by dvershinin** [comment]
@munkee should be fixed in v1.1.0.
Let me know if otherwise. Thanks :)
