### ISSUE TITLE
Implement quiet mode 

### ISSUE THREAD

**Issue by Funeoz** [dvershinin/lastversion#17]
Is it possible for you to implement a `--quiet` tag to prevent lastversion to produce a big output because when I need to log what all my scripts do, I see 100+ lines from lastversion indicating each  download percentage unit.

**Comment by dvershinin** [comment]
@Funeoz there isn't much to hide other than the progress bar, which should degrade properly now (to no output).

So hopefully there's no need for the extra switch. Can you check with the latest release of lastversion, v.1.1.1?

Now, e.g. when piping output to a log, the progress is disabled and those many lines should not be present in the log.

**Comment by Funeoz** [comment]
It's working fine now ! Thank you.

**Comment by dvershinin** [comment]
You're welcome :-)
