### ISSUE TITLE
Releases with underscores / Issues with sourceforge

### ISSUE THREAD

**Issue by atroubat** [dvershinin/lastversion#20]
Hello 
I'm having issues with releases with underscores, for example (https://github.com/squid-cache/squid/releases)
Is it possible to make lastversion parsing releases with underscores? 
Also, Sourceforge links doesn't seem to work properly, I get no results even with your example. 

`[root@centos7 ~]# lastversion https://sourceforge.net/projects/keepass/`
`No release was found`

Can you help me out with that?

Thanks

**Comment by dvershinin** [comment]
@atroubat added a simple attempt at handling those underscores.

As far as SF support, I think it didn't work for you because its support was then unpublished as `lastversion` release.

You can find both changes in v1.1.6 of `lastversion` which is now released.
