### ISSUE TITLE
Using personal token with python code

### ISSUE THREAD

**Issue by falkyre** [dvershinin/lastversion#27]
Hi,

I see how you can use a personal token when you use the command line but is there a way to do the same when using lastversion in python code?

Thanks

**Comment by dvershinin** [comment]
Hi,

You can set it in the environment directly:

```python
import os
from lastversion import lastversion

os.environ['GITHUB_API_TOKEN'] = 'xxxxxxxxxxxxxx'
latest_version = lastversion.has_update(repo="mautic/mautic", current_version='1.2.3')
...
```

**Comment by falkyre** [comment]
Perfect! Thanks.
