### ISSUE TITLE
AttributeError: 'GitHubRepoSession' object has no attribute 'rate_limited_count'

### ISSUE THREAD

**Issue by Galdoni** [dvershinin/lastversion#28]
I got this error while trying to get the latest version of the libraries that were stored in a list. I did by implementing a for loop to check for each library one at a time. 
The error was AttributeError: 'GitHubRepoSession' object has no attribute 'rate_limited_count'.
May I know how to solve this?

**Comment by dvershinin** [comment]
Are you using the latest `lastversion`?
Can you post this list of libraries

**Comment by dvershinin** [comment]
In my testing, this appears to be only happening when using short names of projects that don't exist, and without GitHub API token, e.g. repeatedly running this will trigger the error:

    lastversion this-is-not-in-github-name

@Galdoni ensure GitHub API token is set according to [tips](https://github.com/dvershinin/lastversion#tips) and/or specify full project qualifiers like `owner/name`

**Comment by Galdoni** [comment]
> Are you using the latest `lastversion`?
I'm using version 1.2.3

> Can you post this list of libraries
app-version 1.0.1
appdirs 1.4.4
bandit 1.7.0
beautifulsoup4 4.9.3
cachecontrol 0.12.6
certifi 2020.12.5
chardet 3.0.4
click 7.1.2
colorama 0.4.4
colorclass 2.2.0
feedparser 6.0.2
flask 1.1.2
gitdb 4.0.5
gitpython 3.1.11
idna 2.10
importlib-metadata 3.3.0
itsdangerous 1.1.0
jinja2 2.11.2
lastversion 1.2.3
lockfile 0.12.2
markupsafe 1.1.1
msgpack 1.0.1
packaging 20.8
pbr 5.5.1
pillow 8.0.1
pip 20.3.1
pip-check 2.6
plumbum 1.6.9
pyparsing 2.4.7
python-dateutil 2.8.1
pyyaml 5.3.1
requests 2.25.0
setuptools 39.1.0
sgmllib3k 1.0.0
six 1.15.0
smmap 3.0.4
soupsieve 2.1
stevedore 3.3.0
terminaltables 3.1.0
tqdm 4.54.1
typing-extensions 3.7.4.3
urllib3 1.26.2
werkzeug 1.0.1
winapps 0.1.6
wtforms 2.3.3
zipp 3.4.0

**Comment by Galdoni** [comment]
> nsure GitHub API token is set according t

**Comment by Galdoni** [comment]
> In my testing, this appears to be only happening when using short names of projects that don't exist, and without GitHub API token, e.g. repeatedly running this will trigger the error:
> 
> ```
> lastversion this-is-not-in-github-name
> ```
> 
> @Galdoni ensure GitHub API token is set according to [tips](https://github.com/dvershinin/lastversion#tips) and/or specify full project qualifiers like `owner/name`
> I'm not sure about the API token part, but what I did was putting the library names and current version into a list (like on the comment above). Then, for each element in the list (library name and its current version number), I put it into this statement.
latest_ver = lastversion.has_update(repo=list[0], current_version=list[1])
Followed by if else to determine whether it is outdated.

I've noticed something as well. The error I've mentioned above occurs mostly when it is on the 10th loop.

**Comment by Galdoni** [comment]
The traceback for the error was:
Traceback (most recent call last):
  File "C:/code/PythonLib.py", line 13, in <module>
    latest_ver = lastversion.has_update(repo=i[0], current_version=i[1])
  File "C:\code\lib\site-packages\lastversion\lastversion.py", line 104, in has_update
    latest_version = latest(repo, output_format='version', pre_ok=pre_ok)
  File "C:\code\lib\site-packages\lastversion\lastversion.py", line 46, in latest
    project_holder = HolderFactory.get_instance_for_repo(repo, only=only)
  File "C:\code\lib\site-packages\lastversion\HolderFactory.py", line 67, in get_instance_for_repo
    holder = holder_class(repo, hostname)
  File "C:\code\lib\site-packages\lastversion\GitHubRepoSession.py", line 61, in __init__
    '{}/search/repositories?q={}+in:name'.format(self.api_base, repo))
  File "C:\code\lib\site-packages\lastversion\GitHubRepoSession.py", line 88, in get
    if self.rate_limited_count > 2:
AttributeError: 'GitHubRepoSession' object has no attribute 'rate_limited_count'

Process finished with exit code 1

**Comment by Galdoni** [comment]
May I know, for the scope of the Personal Access Token, which one should I choose, eg repo, workflow etc. Thanks a lot.

**Comment by dvershinin** [comment]
The root cause is that you are providing short project names (not fully qualified) in bulk, and for sure, some of those libraries are not there on GitHub, to begin with. This results in heavy use of GitHub search API, which even when authenticated, is limited to 30 requests per minute.

For personal access token, you can deselect everything, just the bare key is enough to make the necessary API calls.

The new release 1.2.4 of `lastversion` will cache information about the non-existent GitHub repositories, so has reduced API usage.

**Comment by Galdoni** [comment]
I see... I noticed that the documentation for that is mostly targeted for UNIX OS but I'm using Windows OS. 
How do I implement the API token I've got?

**Comment by dvershinin** [comment]
> I see... I noticed that the documentation for that is mostly targeted for UNIX OS but I'm using Windows OS. 
> 
> How do I implement the API token I've got?

Never thought someone would use this on Windows. 

Can you try [these instructions](https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows?mobile_site=true)? Should work.

**Comment by Galdoni** [comment]
> > I see... I noticed that the documentation for that is mostly targeted for UNIX OS but I'm using Windows OS.
> > How do I implement the API token I've got?
> 
> Never thought someone would use this on Windows.
> 
> Can you try [these instructions](https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows?mobile_site=true)? Should work.

It works!! The requests and responses were quick and complete. Thank you very much for your guidance!!
