### ISSUE TITLE
Argument -gt does not work

### ISSUE THREAD

**Issue by just-grizzle** [dvershinin/lastversion#36]
Hi,

I did my first steps with lastversion recently. I wrote some simple script to download DEB packages from Github repositories, if there's a new version availabe. So, nothing unknown for you.

But I could not get the argument `-gt` to work as expected. In fact, if the last version of the repository release is the same as the value to compare with (e.g. not "greater than"), lastversion seems to ignore the argument.

I tried a modification of the script which was described [here](https://github.com/dvershinin/lastversion/issues/19#issuecomment-619549547), too, just to check if it works:
``` shell
LASTVER=$(lastversion dvershinin/lastversion -gt 1.2.6)
echo $LASTVER
if [[ $? -eq 0 ]]; then
  # LASTVER is newer
  echo "Newer version available"
else
  echo "Nothing new"
fi
```

Output:
``` shell
1.2.6
Newer version available
```

Tried several repositories which did not work. So seems like a bug of lastversion.

## My environment:
```
uname -a
Linux vm 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

cat /etc/debian_version
10.7

python3 --version
Python 3.7.3

lastversion --version
lastversion 1.2.6
```

## Tried with repositories
dvershinin/lastversion
cdr/code-server
arendst/tasmota

**Comment by dvershinin** [comment]
@just-grizzle I think what you're facing is the simple bash issue when running in sequence:

```
echo $LASTVER
if [[ $? -eq 0 ]]; then
```

The`$?` in bash stands for exit code of the previously run command, but since it's an `echo`, it will always be successfull....

Remove `echo $LASTVER` or place it in a way that it won't interfere with exit code check.

**Comment by just-grizzle** [comment]
You're right. One should read the README carefully and what you wrote about "Exit Status codes" there. Stupid me.
Thanks nevertheless!
