### ISSUE TITLE
PyPI support

### ISSUE THREAD

**Issue by Galdoni** [dvershinin/lastversion#37]
Hey dvershinin,

May I know for this lastversion module, does it only check those other modules available in GITHUB when doing lastversion.has_update function? There's this python module called lockfile, I've attached the homepage to this module down below. 
I got this question because, in my venv, the lockfile module is already up to date at version 0.12.2, but when I do the has_update function, it shows that the latest version is 2.9.2 instead. 

code:
import lastversion

latest_ver = lastversion.lastversion.has_update(repo="lockfile", current_version="0.12.2")
print(latest_ver)
>> 2.9.2

link to lockfile module:
https://launchpad.net/pylockfile

<img width="287" alt="screenshot" src="https://user-images.githubusercontent.com/76096198/104630506-c8b10800-56d5-11eb-90e4-10026d949c4a.PNG">

**Comment by dvershinin** [comment]
Hi @Galdoni ,

When you're specifying a short single-word for the repo argument, this actually results in searching GitHub for that name.
And the most popular repo is returned and used for version checking. In your case it actually resolved to `greenkeeperio/greenkeeper-lockfile` on GitHub.

To avoid this ambiguity, use a more specific repo name either on GitHub or elsewhere. I actually see that this specific Python module lives at https://github.com/iiiparadoxxxiii/lockfile but no releases were tagged there. The true source of version information for it is at https://pypi.org/project/pylockfile/

There is no support for checking module versions at pypi.org directly. Maybe this should be added as new feature to `lastversion`, e.g.

`lastversion pip/< python lib name>` would unambiguously query pypi.org for version information.

Let me know if it makes sense to implement that.

**Comment by dvershinin** [comment]
Released lastversion 1.3.0 with PyPI support, so you can run:

```
import lastversion

latest_ver = lastversion.lastversion.has_update(repo="lockfile", current_version="0.12.2", at='pip')
print(latest_ver)
```

Although, I'm not pretty sure about this particular project, because the one you mentioned on launchpad is a fork of some kind that is maintained for the specific purpose of OpenStack projects...

**Comment by Galdoni** [comment]
Hi @dvershinin, 

Sorry, I was very busy the past 10 days and I didn't get a chance to follow up on this. I did try out just now and it does come out as the result I wanted. Thank you for your implementation on that. 

I also noticed that the output was faster, even if I commented out the codes for using the GitHub token. So I was wondering whether is it still making requests to GitHub? If not, is the GitHub token still necessary if I'm using at="pip"? 

Thanks.

> Released lastversion 1.3.0 with PyPI support, so you can run:
> 
> ```
> import lastversion
> 
> is_latest_ver = lastversion.lastversion.has_update(repo="lockfile", current_version="0.12.2", at='pip')
> print(is_latest_ver)
> ```
> 
> Although, I'm not pretty sure about this particular project, because the one you mentioned on launchpad is a fork of some kind that is maintained for the specific purpose of OpenStack projects...

**Comment by dvershinin** [comment]
With `at="pip"`, it checks directly with pypi.org JSON API, e.g. [this json](https://pypi.org/pypi/pylockfile/json). So GitHub token isn't used.

**Comment by Galdoni** [comment]
> With `at="pip"`, it checks directly with pypi.org JSON API, e.g. [this json](https://pypi.org/pypi/pylockfile/json). So GitHub token isn't used.

I see... That being said, my issue is solved. Thank you!!
