### ISSUE TITLE
Support GITHUB_TOKEN env.

### ISSUE THREAD

**Issue by stewartbryson** [dvershinin/lastversion#40]
Many other tools, including the GitHub CLI and Hub, use `GITHUB_TOKEN` as the environment variable used to authenticate. In CI/CD environments, this would reduce boilerplate slightly when using your tool along with theirs.

I realize this ticket is not a huge blocker, so feel free to close. But I did want to register the request.

Thanks for a great project. It's very useful.

**Comment by dvershinin** [comment]
Should work fine with lastversion 1.3.1

**Comment by stewartbryson** [comment]
> Should work fine with lastversion 1.3.1

Wow. Thanks for doing this. I’ll check it out.

**Comment by stewartbryson** [comment]
Works as expected. Thank you again.
