### ISSUE TITLE
An invalid link in the lastversion.getpagespeed.com

### ISSUE THREAD

**Issue by ADD-SP** [dvershinin/lastversion#47]
https://lastversion.getpagespeed.com/en/latest/README-ZH-CN/

![网页捕获_1-3-2021_17246_lastversion getpagespeed com](https://user-images.githubusercontent.com/44437200/109477428-f8b04100-7ab2-11eb-9564-2057b4fe4b51.jpeg)

Clicking on the link marked above will return a `404 Note found` status code.

**Comment by dvershinin** [comment]
Should be fine now.
