### ISSUE TITLE
How to set name of downloaded file?

### ISSUE THREAD

**Issue by iainelder** [dvershinin/lastversion#53]
This command downloads a file called rain-v1.2.0_linux-amd64.zip:

```bash
lastversion \
--filter linux-amd64.zip \
--assets \
download https://github.com/aws-cloudformation/rain
```

I want to call the downloaded copy rain.zip (no version at the end) so that it's easier to process in a script.

The --download option is supported to download with a custom filename.

```bash
lastversion \
--filter linux-amd64.zip \
--assets \
--download rain.zip \
download https://github.com/aws-cloudformation/rain
```

But the name of the downloaded file is the same.

Am I missing something?

**Comment by dvershinin** [comment]
The `--download` option worked for source downloads only. In v1.4.1 fixed it up so it works for asset downloads as well.
Please update.

**Comment by iainelder** [comment]
With version 1.4.1 the second command creates a file called rain.zip as expected.

Thanks for the quick resolution.
