### ISSUE TITLE
Apt support

### ISSUE THREAD

**Issue by sharm294** [dvershinin/lastversion#54]
I'm interested in using this for apt repositories. Would you able to add that or accept a pull request if I implemented it?

There's a command line way to do this: [apt-cache madison <pkg_name>](https://askubuntu.com/a/2108/751533), which helpfully prints out the versions available in the correct order from your distro's apt repos as well as any custom ones you've added. I'm not sure if [Python's apt library](https://apt-team.pages.debian.net/python-apt/library/index.html) implements this function or if there's another way to do it but calling that from a subprocess should work fine.

Another thing I was thinking that might be useful was a comparison feature. For example, the standard Ubuntu repos will have older versions of packages than those available through other sources e.g. Github. So maybe you'd be interested to see the latest version of some package from source X but also that there's a newer one available from this other source. One complication with this is that packages in Ubuntu repos will have different names and version formats than their Github counterparts. This is just a secondary idea though.

**Comment by dvershinin** [comment]
I think it's easy to get the current latest version available via repositories with something like `apt info packagename` and parsing the output. How can `lastversion` do it better? I see the use case for the second idea, as in "show me how my distro is behind the actual software versions", but I think we first need to implement installing `.deb` files from GitHub. Similiar to the current feature where lastversion allows installing RPMs from GitHub.

**Comment by sharm294** [comment]
It's not necessarily better but it would be integrated into a common tool so you don't need a bash script to parse out the output. Handling the conversion from Ubuntu package versions to the underlying software version is also something that can hopefully be automated under `lastversion`. Finally, I assumed getting version information from repos would be a prerequisite anyway to comparing how far behind the distro is vs the current release.

I wasn't aware that lastversion could install RPMs from GitHub. It would be good to match support for DEBs here. But I think that's a parallel feature to comparing the distro version to the current version of software because most of these distro packages aren't on GitHub anyway. You'd need to poke around the Debian or Ubuntu repos to get version information.

**Comment by dvershinin** [comment]
I've added a simple fetching of latest version available from `apt`, `yum` and `dnf`. Can be requested with the `--at system` switch.

@sharm294 you can test from master:

```bash
apt -y install git python3-pip python3-apt
python3 -m pip install git+https://github.com/dvershinin/lastversion.git
```

Then this is possible:

```console
root@af621fea9a72:/# lastversion git --at system
2.25.1
root@af621fea9a72:/# lastversion git
2.33.0
```

Comparing against system/GitHub version in one command may be implemented. But there likely to be many false positive if GitHub search by name yieds an irrelevant repo. In apt, there seems to be no link to original URL of a project. In rpm, there's actually URL field for a package, which could be used as it often links to a GitHub URL...
