### ISSUE TITLE
missing dash in release version retrieved

### ISSUE THREAD

**Issue by dkebler** [dvershinin/lastversion#58]
at this repo
https://github.com/Aircoookie/WLED/releases
notice the latest is 0.13.0-b2
that's dash -b2
lastversion is returning pre-release version without that dash, which sadly breaks the downloads etc. without me doing some extra sed manipulation

```
> lastversion --pre Aircoookie/WLED
> 0.13.0b2
```

installed lastversion via pip, 3.02

**Comment by dkebler** [comment]
for now I just added a sed
```
ver=$(lastversion --pre Aircoookie/WLED)
ver=$(sed -e s/b/-b/ <<< "$ver")
```

**Comment by dvershinin** [comment]
lastversion normalizes versions according to [PEP 440 Version Identification and Dependency Specification](https://www.python.org/dev/peps/pep-0440/). So `0.13.0b2` is a more or less canonical version (while others can put it as `-b2` or `-beta2` or whatever fancy format which lacks any consistency).

To get an unmodified release tag, you can do:

```console
[user@pc ~]# lastversion --pre Aircoookie/WLED --format json | jq -r .tag_name
v0.13.0-b2
```

> breaks the downloads etc.

Or better yet, get the desired download URLs from `lastversion` itself:

```console

[user@pc ~]# lastversion --pre Aircoookie/WLED --format source
https://github.com/Aircoookie/WLED/archive/v0.13.0-b2/WLED-v0.13.0-b2.tar.gz


[user@pc ~]# lastversion --pre Aircoookie/WLED --format assets
https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/esp32_bootloader_v2.bin
https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/WLED_0.13.0-b2_ESP01.bin
https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/WLED_0.13.0-b2_ESP32.bin
https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/WLED_0.13.0-b2_ESP32_Ethernet.bin
https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/WLED_0.13.0-b2_ESP8266.bin

```

Lastly, lastversion can do downloads for you:

```
lastversion download --pre Aircoookie/WLED 
```

etc.

**Comment by dvershinin** [comment]
I forgot that for the bare tag name, you can use `--format tag`, e.g.:

> lastversion --pre Aircoookie/WLED --format tag

But still, I highly recommend checking the `download` command of lastversion. You don't need un-normalized versions.

**Comment by dkebler** [comment]
all good info thx!

my script downloads a particular asset so download option not useful in my case, unless there is a way to tell lastversion to download a particular asset of the set instead of the source?

**Comment by dkebler** [comment]
well yes it can get the asset url which avoids my issue
but can it download that instead of the source?

`lastversion --pre Aircoookie/WLED --format assets --filter ESP32.bin`

> `https://github.com/Aircoookie/WLED/releases/download/v0.13.0-b2/WLED_0.13.0-b2_ESP32.bin`

**Comment by dvershinin** [comment]
@dkebler looks like it can, if invoked like this:

> lastversion download Aircoookie/WLED --pre --format assets --filter ESP32.bin

**Comment by dkebler** [comment]
ok ha it can

`lastversion --pre Aircoookie/WLED --format assets --filter ESP32.bin -d ESP32.bin`

I think you should add this example to your readme.    Many times it's a particular asset that needs to be downloaded (like a binary for particular platform)

**Comment by dkebler** [comment]
Just ending this by thanking you again.  I have all kinds of bash and nodejs scripts I've written to get repo release assets from different projects but with lastversion I can dump/simplify all those.  This is a small BUT very useful project.
