### ISSUE TITLE
later unreleased tags shown on private repos`

### ISSUE THREAD

**Issue by d4nshields** [dvershinin/lastversion#68]
Hi, I have a private repo that I am using lastverison with (using GITHUB_TOKEN env variable for authentication).   I am seeing it return a later tag than the latest release, not sure why.    I didn't see this issue with any public repository I tried.

The issue can be demonstrated in the well-known EpicGames/UnrealEngine repository:

    $ lastversion EpicGames/UnrealEngine
    4.27.3

However, https://github.com/EpicGames/UnrealEngine/releases shows 'Unreal Engine 4.27.2 (latest)'.

I have attached the -v log output, if thay helps.

[lastversion-bug-logoutput.txt](https://github.com/dvershinin/lastversion/files/7942911/lastversion-bug-logoutput.txt)

**Comment by dvershinin** [comment]
@d4nshields it was actually failing to recognize `4.27-chaos-preview-3` as a beta tag. 
Can you try `lastversion` from git? This should have the fix for this (added just now).

**Comment by d4nshields** [comment]
The latest build from git is returning the correct version in this test case:

    $ dist/lastversion EpicGames/UnrealEngine
    4.27.2
