### ISSUE TITLE
Handle full URL

### ISSUE THREAD

**Issue by jayvdb** [dvershinin/lastversion#7]
Often a script has the full URL , and while it is easy enough to cut the string in half, it would be useful it let lastversion handle it.

```console
> python3 -m lastversion --source http://github.com/Yelp/swagger_spec_validator
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}No release was found
```

This might also be useful for supported enterprise GitHub which have their own domain.

**Comment by dvershinin** [comment]
@jayvdb , it actually did this for `https://` URLs (and accepts things like `https://github.com/Yelp/swagger_spec_validator/any/link/inside`, but in your example, it's insecure `http://`, so it didn't work. 

I've added handling non-Github (enterprise) hostnames, and `http://` will work as well (although the resulting links will still be `https://` for simplicity.

**Comment by jayvdb** [comment]
Thanks!
