### ISSUE TITLE
Can you support gitea?

### ISSUE THREAD

**Issue by MisileLab** [dvershinin/lastversion#73]
[Release docs](https://gitea.com/api/swagger#/repository/repoListReleases)

**Comment by dvershinin** [comment]
Yep, will use [their repo](https://gitea.com/gitea/tea) as a test first.

**Comment by dvershinin** [comment]
@MisileLab in v2.4.5 introduced Gitea support. Invocation like the following:

```
lastversion https://gitea.com/gitea/tea #>  0.8.0
lastversion gitea/tea --at gitea #> 0.8.0
lastversion download https://gitea.com/gitea/tea
```

**Comment by MisileLab** [comment]
> @MisileLab in v2.4.5 introduced Gitea support. Invocation like the following:
> 
> ```
> lastversion https://gitea.com/gitea/tea #>  0.8.0
> lastversion gitea/tea --at gitea #> 0.8.0
> lastversion download https://gitea.com/gitea/tea
> ```

thank you!
