### ISSUE TITLE
Fetch assets

### ISSUE THREAD

**Issue by jayvdb** [dvershinin/lastversion#8]
What about adding support for fetching the specified assets?

**Comment by dvershinin** [comment]
Example, please? What about the `--assets --filter REGEX` which is already there:

    $ lastversion https://github.com/xmrig/xmrig/ --assets --filter xenial

Gives `https://github.com/xmrig/xmrig/releases/download/v3.1.2/xmrig-3.1.2-xenial-x64.tar.gz`

**Comment by jayvdb** [comment]
I mean actually downloading the tarballs.  I couldn't see a way to do that

**Comment by dvershinin** [comment]
Why not just `curl` or `wget` the output as in the examples:

    wget $(lastversion --assets mautic/mautic)

`curl` is everywhere so can work too:

    lastversion --assets mautic/mautic | xargs -n 1 curl -OLs

**Comment by jayvdb** [comment]
Laziness.

But also it allows adding logic to standardise/prettify/de-GitHub-ify the file names of the fetched files.

Anyways, no worries if you would rather avoid adding this feature.

**Comment by dvershinin** [comment]
Maybe laziness wins. I added the `-d` (or `--download`), which will by default download the source archive, and if you want to customize the downloaded filename, you can do so by `-d foo.tar.gz`.
