### ISSUE TITLE
--assets return empty value

### ISSUE THREAD

**Issue by Olivier6767** [dvershinin/lastversion#88]
When trying to retrieve the assets list from `distribworks/dkron` (github) it returns an empty list.
However using the link [asset list](https://api.github.com/repos/distribworks/dkron/releases/77487763/assets) we can see a list of assets.

Is there a way to display these in lastversion?

**Comment by dvershinin** [comment]
By default, `lastversion` filters out assets based on platform, to give you the ones "you want".
Perhaps the matching has failed for some reason. You can ignore the platform matching with `--filter .`:

```console
lastversion --assets --filter . distribworks/dkron
```

**Comment by Olivier6767** [comment]
Great! Thanks.
