### ISSUE TITLE
Support Even/Odd and 90+ Version Schemes

### ISSUE THREAD

**Issue by danyeaw** [dvershinin/lastversion#89]
Lastversion is supposed to return the latest stable versions, and often it returns an unstable version. For example:

```
> lastversion https://gitlab.gnome.org/GNOME/gtk
4.9.2
```
However the latest stable version is 4.8.3.

Many open-source projects, especially in the Linux ecosystem, use alternatives to semver or calver to indicate that a release is an unstable version:

1. Even/Odd versioning with 1.2.0 being stable and 1.3.0 being unstable
2. 90+ versioning with 1.2.10 being stable and 1.2.90 being unstable

Although there is probably no way for lastversion to know that a project is using one of those schemes, maybe we could add an additional option to explicitly declare that a project is using them?

**Comment by dvershinin** [comment]
In the `https://gitlab.gnome.org/GNOME/gtk` there's really no designation of stability on tags that I see, whatsoever.
My interpretation still is that 4.9.2 somewhat stable but conservatively speaking and from their point, it's "preview".
They don't seem to define what's stable by any means other than their website. 

We could use [Wikipedia](https://en.wikipedia.org/wiki/GTK) as a second source of truth.

Can you please provide other such repository examples?

**Comment by dvershinin** [comment]
FYI, this does work with the correct result:

```console
lastversion https://en.wikipedia.org/wiki/GTK
4.8.3
```

**Comment by dvershinin** [comment]
Very interesting. 

I wasn't aware of the .90+ thing. For this, I'd probably just have it added without an extra switch: to treat any x.x.90+ as unstable (since there are, I assume, no real projects with that many stable releases).

For the odd/even, add an `--even` switch?. Let me know your thoughts.

**Comment by danyeaw** [comment]
That sounds great to me! 👍

**Comment by dvershinin** [comment]
Added in lastversion 2.4.9

**Comment by danyeaw** [comment]
@dvershinin Thanks, that's a great update!

I did notice for one of the examples above:

```
> lastversion --even https://gitlab.gnome.org/GNOME/gobject-introspection
1.72.1
```

It should have return 1.74.0, which is the newest stable version. However, 1.72.1 was release just after 1.74.0.

**Comment by dvershinin** [comment]
@danyeaw please check lastversion v2.4.10. Addressed that issue.

**Comment by danyeaw** [comment]
Thanks @dvershinin!
