### ISSUE TITLE
[enhancement] Linux auto filter

### ISSUE THREAD

**Issue by virgilwashere** [dvershinin/lastversion#9]
https://github.com/dvershinin/lastversion/blob/5e07cc9c5cb126a00c7508483b49e21908fdebdf/lastversion/lastversion.py#L24

## Enhancement for `posixAssetMarkers`

Can you please

- [ ] expand `-` (hyphen) to `(-|_)` (hyphen OR underscore)

- [ ] add `?linux?amd64`

- [ ] add `?amd64`

Thanks.

**Comment by dvershinin** [comment]
@virgilwashere Could you give examples of the latter two?

**Comment by virgilwashere** [comment]
github/hub --assets --linux

**Comment by dvershinin** [comment]
@virgilwashere let me know how it goes in the latest release. This should work well in x86_64 systems (most common I think) because it now attempts to also filter out non-matching architectures. Surely this can never be a complete solution, but at least something :)

```
# on x86_64 machine:
lastversion github/hub --assets # no filter flag
# should only give:
https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz
```

**Comment by virgilwashere** [comment]
> because it now attempts to also filter out non-matching architectures.

working OK on other repos, 

```console
$ lastversion github/hub --assets
https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz
```

until.... 🎬 

```console
$ lastversion junegunn/fzf-bin --assets
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_amd64.tgz
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_arm5.tgz
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_arm6.tgz
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_arm7.tgz
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-linux_arm8.tgz
https://github.com/junegunn/fzf-bin/releases/download/0.18.0/fzf-0.18.0-openbsd_amd64.tgz

# WSL
$ uname -a
Linux firefly 4.4.0-18362-Microsoft #10000-Microsoft Fri Jun 21 11:23:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

```



😢

**Comment by dvershinin** [comment]
We want to return as many applicable assets as possible (who knows, what if repo has a bunch of different OS assets plus some data asset). 

So I'm following the "blacklist" approach (remove known inapplicable arches/platforms). Any asset name that does not have "linux" in it, is still returned on Linux. Unless it is "blacklisted". 

I have added `arm[0-9]` to be blacklisted on `x86_64` as well as `openbsd` to be blacklisted for when you run `lastversion` in Linux.

See if this helps and if we can improve further in other repos.
