### ISSUE TITLE
Wrong version listed unless --pre is passed

### ISSUE THREAD

**Issue by henryiii** [dvershinin/lastversion#90]
If I run:

```
pipx run lastversion https://github.com/charliermarsh/ruff-pre-commit
```

For some reason I get 0.0.89, when the latest version is 0.0.246. Even if I pass `--newer-than 0.0.200`, I still get 0.0.89. However, it starts working if I pass `--pre`. I'm not sure how `0.0.89` could be a non-pre-release while `0.0.246` is a pre-release? They are just git tags, not full GitHub releases.

**Comment by dvershinin** [comment]
It should be fixed in the latest `lastversion` release. The reason was that in the prior release, we added a feature that sees x.x.90+ as pre-releases because a number of projects use this convention to mark betas. Now **0.0**.90+ is not seen as a pre-release.

**Comment by henryiii** [comment]
Thanks! Hopefully Ruff doesn't hit 0.0.900...
