### ISSUE TITLE
Exclude option not working as expected

### ISSUE THREAD

**Issue by vaz-ar** [dvershinin/lastversion#95]
Hello,

I am trying to get the latest available version for `gomplate`:

~~~bash
❯ lastversion hairyhenderson/gomplate
4.0.0.0
~~~

I was expecting to get `3.11.4`, so I went and looked in the verbose output and saw that there is a `v4.0.0-pre-0` tag (https://github.com/hairyhenderson/gomplate/releases/tag/v4.0.0-pre-0) that is causing problems here.
I though that this could be solved by using the `--exclude` option, which from what I can see in the help message should allow to filter using a regular expression.

I tried the following:
 
~~~bash
❯ lastversion --exclude 'v4.0.0-pre-0' hairyhenderson/gomplate
4.0.0.0

❯ lastversion --exclude 'v4\.0\.0-pre-0' hairyhenderson/gomplate
4.0.0.0

❯ lastversion --exclude '4.0.0.0' hairyhenderson/gomplate
4.0.0.0

❯ lastversion --exclude '4\.0\.0\.0' hairyhenderson/gomplate
4.0.0.0

❯ lastversion --exclude '4\..+' hairyhenderson/gomplate
4.0.0.0

❯ lastversion --exclude 'v4\..+' hairyhenderson/gomplate
4.0.0.0
~~~

Am I mistaken in how the `exclude` flag is supposed to work ? Or is there another problem here ?

**Comment by dvershinin** [comment]
So there was 1) a bug that `--exclude` did not apply, and 2) we could better detect pre-releases. It should work in the new lastversion v2.4.13 as expected just `lastversion hairyhenderson/gomplate` without the exclusion filter.
