### ISSUE TITLE
It is not working, while i include only and exclude rc.

### ISSUE THREAD

**Issue by Pranav-Lakhani** [dvershinin/lastversion#96]
Hi,

I am trying to get in my script latest version of lightning which is : lnd v0.16.0-beta

lastversion --only 'beta' https://github.com/lightningnetwork/lnd --format tag
returning me rc release : v0.16.0-beta.rc4 ( where there more latest release and final release are there) I have tried all option but still not getting correct version.

**Comment by dvershinin** [comment]
You need `--pre` because it is beta you are looking for, and also because that repository hosts a number of software, exclude both `rc` and the unwanted software tags:

```bash
lastversion --pre --exclude "~(cert|kvdb|tlv|rc)" https://github.com/lightningnetwork/lnd --format tag
```

**Comment by dvershinin** [comment]
That said, in *this case* I would raise an issue with the upstream. What is their thinking when making tag `v0.16.0-beta.rc4`. It is confusing what they mean by this. Usually, there is a beta followed by a release candidate. But they have both at the same time... Is it RC4 of beta? Is it beta of RC4? or just RC4 or just beta4 :)
