### ISSUE TITLE
Add option to use previous release if latest release contains no assets that match given filter

### ISSUE THREAD

**Issue by cobalt2727** [dvershinin/lastversion#97]
I'm automating updates for a repo that failed to build their latest version for arm64 - it would be nice to have a fallback:

https://github.com/minecraft-linux/appimage-builder/releases/tag/v0.9.0-713
![image](https://user-images.githubusercontent.com/60624944/230476550-d670fca7-3714-4ebd-b687-d447a308a550.png)

**Comment by dvershinin** [comment]
@cobalt2727 I've dealt with a similar issue and think there's already an option for you :-) 

```bash
lastversion --having-asset ~arm64 minecraft-linux/appimage-builder 
```

**Comment by cobalt2727** [comment]
Thanks! Is this in the documentation anywhere?

**Comment by dvershinin** [comment]
Yes, there's a section in the README that goes `Use case: releases with specific assets`
